// Marker on every streamed island so tools, other scripts and the editor can
// see what it is (name, biome, radius). The geometry itself is generated by
// the WorldStreamer from the world seed.
defineScript({
  name: 'Island',
  description: 'Identifies a generated floating island.',
  props: {
    id: { type: 'integer', default: 0 },
    name: { type: 'string', default: 'Island' },
    biome: { type: 'string', default: 'meadow' },
    radius: { type: 'number', default: 18 },
  },
});
